# Generated by Django 4.1.13 on 2024-11-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="id",
            new_name="customer_id",
        ),
    ]
