# Generated by Django 4.1.13 on 2024-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Grocery', 'Grocery'), ('Furniture', 'Furniture'), ('Toys', 'Toys')], default='Electronics', max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_id', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.TextField(blank=True)),
                ('product_image', models.URLField(blank=True, default='https://img-b.udemycdn.com/course/750x422/6072899_3371_18.jpg')),
            ],
        ),
    ]
